name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Authenticate in Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Build and push Docker image to Google Artifact Registry"
        run: "gcloud builds submit --tag us-central1-docker.pkg.dev/notely-495501/notely-ar-repo/notely:latest ."

      - name: Migrate database
        run: npm run db:migrate

      - name: "Deploy to Cloud Run"
        run: "gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-495501/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-495501 --max-instances=4"
